apiVersion: apps/v1
kind: Deployment
metadata:
  name: wm-address
spec:
  replicas: 1
  selector:
    matchLabels:
      app: address
      role: backend
      scs: wm
  template:
    metadata:
      labels:
        app: address
        role: backend
        scs: wm
    spec:
      containers:
      - name: wm-address
        image: chrisburki/wm-address
        imagePullPolicy: Always
        ports:
        - protocol: TCP
          containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: wm-address
spec:
  selector:
    app: address
    role: backend
    scs: wm
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: NodePort
