apiVersion: apps/v1
kind: Deployment
metadata:
  name: wm-customer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customer
      role: backend
      scs: wm
  template:
    metadata:
      labels:
        app: customer
        role: backend
        scs: wm
    spec:
      containers:
        - name: wm-customer
          image: chrisburki/wm-customer
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              protocol: TCP
          readinessProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 80
            initialDelaySeconds: 3
            periodSeconds: 3

---

apiVersion: v1
kind: Service
metadata:
  name: wm-customer
spec:
  selector:
    app: customer
    role: backend
    scs: wm
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: NodePort
