apiVersion: apps/v1
kind: Deployment
metadata:
  name: wm-customer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customer
      role: backend
      scs: wm
  template:
    metadata:
      labels:
        app: customer
        role: backend
        scs: wm
    spec:
      containers:
        - name: wm-customer
          image: chrisburki/wm-customer
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              protocol: TCP
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 1
            successThreshold: 1
          livenessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 20
            timeoutSeconds: 2
            failureThreshold: 1
            successThreshold: 1

---

apiVersion: v1
kind: Service
metadata:
  name: wm-customer
spec:
  selector:
    app: customer
    role: backend
    scs: wm
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  type: NodePort
