apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper
      role: backend
      scs: wm
  template:
    metadata:
      labels:
        app: zookeeper
        role: backend
        scs: wm
    spec:
      containers:
      - name: zookeeper
        image: bitnami/zookeeper
        imagePullPolicy: Always
        ports:
        - containerPort: 2181
        env:
        - name: ALLOW_ANONYMOUS_LOGIN
          value: "yes"
        - name: ZOOKEEPER_ID
          value: "1"
        - name: ZOOKEEPER_SERVER_1
          value: zookeeper

---
apiVersion: v1
kind: Service
metadata:
  name: wzookeeper
spec:
  selector:
    app: zookeeper
    role: backend
    scs: wm
  ports:
  - name: client
    port: 2181
    protocol: TCP          
  - name: follower
    port: 2888
    protocol: TCP
  - name: leader
    port: 3888
    protocol: TCP
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
      role: backend
      scs: wm
  template:
    metadata:
      labels:
        app: kafka
        role: backend
        scs: wm
    spec:
      containers:
      - name: kafka
        image: bitnami/kafka
        imagePullPolicy: Always
        ports:
        - protocol: TCP
          containerPort: 9092
        env:
        - name: ENABLE_AUTO_EXTEND
          value: "true"
        - name: KAFKA_RESERVED_BROKER_MAX_ID
          value: "999999999"
        - name: KAFKA_AUTO_CREATE_TOPICS_ENABLE
          value: "true"
        - name: KAFKA_PORT
          value: "9092"
        - name: KAFKA_ADVERTISED_PORT
          value: "9092"
        - name: KAFKA_ADVERTISED_HOST_NAME
          value: "kafka"
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: zookeeper:2181
        - name: ALLOW_PLAINTEXT_LISTENER
          value: "yes"

---
apiVersion: v1
kind: Service
metadata:
  name: kafka
spec:
  selector:
    app: kafka
    role: backend
    scs: wm
  ports:
  - name: kafka-port
    protocol: TCP
    port: 9092
  type: ClusterIP


