apiVersion: apps/v1
kind: Deployment
metadata:
  name: wm-zookeeper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper
      role: backend
      scs: wm
  template:
    metadata:
      labels:
        app: zookeeper
        role: backend
        scs: wm
    spec:
      containers:
      - name: wm-zookeeper
        image: bitnami/zookeeper
        imagePullPolicy: Always
        ports:
        - protocol: TCP
          containerPort: 2181
        env:
        - name: ALLOW_ANONYMOUS_LOGIN
          value: "yes"

---
apiVersion: v1
kind: Service
metadata:
  name: wm-zookeeper
spec:
  selector:
    app: zookeeper
    role: backend
    scs: wm
  ports:
  - protocol: TCP          
    port: 2181
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
      role: backend
      scs: wm
  template:
    metadata:
      labels:
        app: kafka
        role: backend
        scs: wm
    spec:
      containers:
      - name: kafka
        image: bitnami/kafka
        imagePullPolicy: Always
        ports:
        - protocol: TCP
          containerPort: 9092
        env:
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: wm-zookeeper:2181
        - name: ALLOW_PLAINTEXT_LISTENER
          value: "yes"

---
apiVersion: v1
kind: Service
metadata:
  name: kafka
spec:
  selector:
    app: kafka"
    role: backend
    scs: wm
  ports:
  - protocol: TCP
    port: 9092
  type: ClusterIP


