apiVersion: apps/v1
kind: Deployment
metadata:
  name: wm-pubsub
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pubsub
      role: backend
      scs: wm
  template:
    metadata:
      labels:
        app: pubsub
        role: backend
        scs: wm
    spec:
      volumes:
      - name: gcloud-wm-pubsub-key
        secret:
          secretName: wm-pubsub-key
      containers:
      - name: wm-pubsub
        image: chrisburki/wm-pubsub
        imagePullPolicy: Always
        ports:
        - protocol: TCP
          containerPort: 8080
        volumeMounts:
        - name: gcloud-wm-pubsub-key
          mountPath: /var/secrets/google
        env:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /var/secrets/google/key.json

---
apiVersion: v1
kind: Service
metadata:
  name: wm-pubsub
spec:
  selector:
    app: pubsub
    role: backend
    scs: wm
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: NodePort